<div id="bb-insta-wdg" class="generic-content">
    <strong id="bb-insta-title"><!-- @channel--></strong>
    <ul id="bb-insta-stream">
        <!-- widget instagram stream-->
    </ul>
</div>
<script type="text/x-magento-init">
    {
        "#bb-insta-wdg": {
            "InstagramWidget": {
                "token":"4051544892.c0d60c0.4216b9d182ed403eac4965a43a3c954c",
                "userid":"4051544892",
                "channel":"@AwesomeChannel",
                "num_photos":"4"
            }
        }
    }
</script>

