<?php
/**
 * Instagram Widget block template
 *
 * @var $block \Bitbull\InstagramWidget\Block\Instagram
 */
?>
<div id="bb-insta-wdg" class="generic-content">
    <strong id="bb-insta-title"><!-- @channel--></strong>
    <ul id="bb-insta-stream">
        <!-- widget instagram stream-->
    </ul>
</div>
<script type="text/x-magento-init">
    {
        "#bb-insta-wdg": {
            "InstagramWidget": <?php echo \Zend_Json::encode($block->getConfig()) ?>
        }
    }
</script>