<script>
  require(['jquery'], function($){

    //<![CDATA[

    var endpoint = 'https://api.instagram.com/oauth/';
    var loginWindow = 'InstagramLogin';
    var clientId = $('#<?php /* @escapeNotVerified */ echo $block->getClientIdField(); ?>').val();
    var clientSecret = $('#<?php /* @escapeNotVerified */ echo $block->getClientSecretField(); ?>').val();
    var pageKey = '<?php /* @escapeNotVerified */ echo $this->getRequest()->getParam('key'); ?>';

    function getCode() {

      var urlParams = new URLSearchParams(window.location.search);
      return urlParams.get('code');

    }

    function getToken(code) {

      var params = {
        "client_id": clientId,
        "client_secret": clientSecret,
        "grant_type": "authorization_code",
        "redirect_uri": "http://www.goldenpoint.local/admin/admin/system_config/edit/section/bitbull_instagramwidget/?key=" + pageKey,
        "code": code
      };

      $.ajax({
        url: endpoint + 'access_token/',
        dataType: 'json',
        type: 'POST',
        data: params,
        success: function(data) {
          window.opener.document.getElementById('<?php /* @escapeNotVerified */ echo $block->getTokenField(); ?>').value = data.access_token;
          window.opener.document.getElementById('<?php /* @escapeNotVerified */ echo $block->getUserIdField(); ?>').value = data.user.id;
          window.close();
        },
        error: function(data) {
          console.error('Error: '+ data.error_message);
          window.document.write('Something went wrong, ensure you have correctly configure the valid redirect URIs in your Instagram App and try again.')
        }
      });

    }

    function getInstagramAccess() {

      if (!clientId && !clientSecret) {
        alert('Please, fill in the Client Id and the Client Secret fields to generate a new token');
        return false;
      }

      window.open(endpoint + 'authorize/?client_id=' + clientId + '&redirect_uri=http://www.goldenpoint.local/admin/admin/system_config/edit/section/bitbull_instagramwidget/?key='+ pageKey +'&response_type=code', loginWindow, 'toolbar=no,scrollbars=no,resizable=no,top=300,left=400,width=400,height=600');

    }

    if (window.name === loginWindow) {
      window.addEventListener('load', function () {
        console.log(window.name);
        var code = getCode();
        console.log(code);
        if (code) {
          window.document.write('Connecting..');
          getToken(code);
        }
      });
    }

    window.getInstagramAccess = getInstagramAccess;

//]]>

  });
</script>

<div class="pp-buttons-container">
  <button type="button" id="<?php echo $block->getId() ?>" onclick="window.getInstagramAccess()">
    <span><?php echo $block->escapeHtml($block->getButtonLabel()); ?></span>
  </button>
</div>